In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from collections import Counter

In [2]:
# read the train and test csv files

train_df = pd.read_csv('original_data/train.csv')
test_df = pd.read_csv('original_data/test-3.csv', index_col='index') # no need to read the index column

## Data Exploration, Data Cleaning

Let us examine the dataframes and their columns

In [3]:
train_df

AC    AF   AR    AS  AST   AY       AwayTeam      Date FTR    HC  \
0       3.0  12.0  0.0  14.0  4.0  0.0      Stuttgart  07/08/09   H   6.0   
1       1.0  10.0  0.0   7.0  0.0  1.0        FC Koln  08/08/09   H  16.0   
2       3.0  20.0  0.0  15.0  3.0  2.0       Hannover  08/08/09   H   5.0   
3      10.0  28.0  0.0   9.0  3.0  2.0  Bayern Munich  08/08/09   D   3.0   
4       5.0  28.0  0.0  13.0  7.0  2.0     Leverkusen  08/08/09   D   3.0   
...     ...   ...  ...   ...  ...  ...            ...       ...  ..   ...   
12784   7.0   1.0  0.0  17.0  4.0  1.0        Udinese  28/05/17   H   6.0   
12785   7.0  16.0  0.0  17.0  4.0  4.0         Empoli  28/05/17   H   0.0   
12786   2.0  14.0  0.0  13.0  4.0  0.0          Genoa  28/05/17   H   6.0   
12787  10.0   8.0  0.0  22.0  7.0  0.0         Napoli  28/05/17   A   5.0   
12788  10.0   6.0  0.0  21.0  7.0  0.0       Sassuolo  28/05/17   H   6.0   

         HF   HR    HS   HST  HTAG  HTHG   HY    HomeTeam      league  
0      12.0  0.0  13.0   7.0   0.0   0.0  0.0   Wolfsburg  bundesliga  
1       8.0  0.0  24.0  11.0   0.0   0.0  0.0    Dortmund  bundesliga  
2      16.0  0.0  10.0   4.0   0.0   0.0  3.0      Hertha  bundesliga  
3      10.0  0.0   9.0   1.0   1.0   1.0  0.0  Hoffenheim  bundesliga  
4      22.0  0.0   8.0   4.0   2.0   1.0  1.0       Mainz  bundesliga  
...     ...  ...   ...   ...   ...   ...  ...         ...         ...  
12784  15.0  0.0  17.0   6.0   0.0   3.0  2.0       Inter     serie-a  
12785  18.0  0.0  10.0   5.0   0.0   0.0  3.0     Palermo     serie-a  
12786   8.0  0.0  24.0   7.0   1.0   1.0  2.0        Roma     serie-a  
12787   9.0  0.0  12.0   2.0   2.0   0.0  1.0   Sampdoria     serie-a  
12788  16.0  0.0  16.0   9.0   2.0   3.0  2.0      Torino     serie-a  

[12789 rows x 19 columns]

In [4]:
test_df

AC  AF  AR  AS  AST  AY       AwayTeam      Date  HC  HF  HR  HS  HST  \
index                                                                          
0       5  17   0  19    4   2     Leverkusen  18/08/17   4  13   0  13    8   
1       7  16   0  13    1   3       Augsburg  19/08/17   3  18   0  11    5   
2       1  12   0   9    2   1      Stuttgart  19/08/17   5  18   0  10    3   
3       4  15   0  11    2   3  Werder Bremen  19/08/17   6  17   0  14    3   
4       1  14   0   6    2   5       Hannover  19/08/17  13  18   0  14    6   
...    ..  ..  ..  ..  ...  ..            ...       ...  ..  ..  ..  ..  ...   
375     1   5   1   9    3   1     Fiorentina  20/05/18   6  10   0  18   11   
376     9   9   0   9    4   0        Crotone  20/05/18   6   3   0  19    9   
377     9   8   0  15    6   1           Roma  20/05/18   5  14   0  16    3   
378     3  11   0   9    3   4      Sampdoria  20/05/18   5  10   0  16    6   
379     2  11   0   8    5   2        Bologna  20/05/18  10   9   0  20    5   

       HTAG  HTHG  HY       HomeTeam Referee      league  
index                                                     
0         0     2   1  Bayern Munich     NaN  bundesliga  
1         0     1   4        Hamburg     NaN  bundesliga  
2         0     0   2         Hertha     NaN  bundesliga  
3         0     0   1     Hoffenheim     NaN  bundesliga  
4         0     0   3          Mainz     NaN  bundesliga  
...     ...   ...  ..            ...     ...         ...  
375       1     2   2          Milan     NaN     serie-a  
376       0     2   0         Napoli     NaN     serie-a  
377       1     0   1       Sassuolo     NaN     serie-a  
378       0     1   1           Spal     NaN     serie-a  
379       0     1   0        Udinese     NaN     serie-a  

[1826 rows x 19 columns]

In [5]:
train_df.columns

Index(['AC', 'AF', 'AR', 'AS', 'AST', 'AY', 'AwayTeam', 'Date', 'FTR', 'HC',
       'HF', 'HR', 'HS', 'HST', 'HTAG', 'HTHG', 'HY', 'HomeTeam', 'league'],
      dtype='object')

In [6]:
test_df.columns

Index(['AC', 'AF', 'AR', 'AS', 'AST', 'AY', 'AwayTeam', 'Date', 'HC', 'HF',
       'HR', 'HS', 'HST', 'HTAG', 'HTHG', 'HY', 'HomeTeam', 'Referee',
       'league'],
      dtype='object')

In [7]:
print(f"Number of columns in train_df = {len(train_df.columns)}")
print(f"Number of columns in test_df = {len(test_df.columns)}")

Number of columns in train_df = 19
Number of columns in test_df = 19


At first glance, there is a `Referee` column in the test dataset which is not in the train dataset.
In the train df, the FTR (what we should predict) appears but not in the test df, as it should.  

Let us find out if there are more such columns.

In [8]:
commonColumns = set(list(train_df.columns)).intersection(set(list(test_df.columns))) # between train and test dataframes
print(sorted(commonColumns), f"i.e. {len(commonColumns)} columns are common between train_df and test_df")

['AC', 'AF', 'AR', 'AS', 'AST', 'AY', 'AwayTeam', 'Date', 'HC', 'HF', 'HR', 'HS', 'HST', 'HTAG', 'HTHG', 'HY', 'HomeTeam', 'league'] i.e. 18 columns are common between train_df and test_df


In [9]:
set(list(train_df.columns)) - commonColumns  # columns only in train_df

{'FTR'}

In [10]:
set(list(test_df.columns)) - commonColumns  # columns only in test_df

{'Referee'}

The referee should not influence the outcome of the game. So, we can safely drop that column in test_df.  

As we train our model, FTR column is not one of the predictors since that is what we are predicting. We drop this too for training. 

So, both the train and test dataframes will have the same columns once we drop these columns from the respective dataframes.

Let us check the datatypes and missing values in the two DFs.

In [11]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12789 entries, 0 to 12788
Data columns (total 19 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   AC        12780 non-null  float64
 1   AF        12778 non-null  float64
 2   AR        12780 non-null  float64
 3   AS        12780 non-null  float64
 4   AST       12780 non-null  float64
 5   AY        12780 non-null  float64
 6   AwayTeam  12782 non-null  object 
 7   Date      12782 non-null  object 
 8   FTR       12782 non-null  object 
 9   HC        12780 non-null  float64
 10  HF        12778 non-null  float64
 11  HR        12780 non-null  float64
 12  HS        12780 non-null  float64
 13  HST       12780 non-null  float64
 14  HTAG      12779 non-null  float64
 15  HTHG      12779 non-null  float64
 16  HY        12779 non-null  float64
 17  HomeTeam  12782 non-null  object 
 18  league    12789 non-null  object 
dtypes: float64(14), object(5)
memory usage: 1.9+ MB


Almost every column in train_df except the "league" has null values.  Even the FTR column i.e. the result column has 7 missing values. We will deal with these missing values later in this notebook.

In [12]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1826 entries, 0 to 379
Data columns (total 19 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   AC        1826 non-null   int64 
 1   AF        1826 non-null   int64 
 2   AR        1826 non-null   int64 
 3   AS        1826 non-null   int64 
 4   AST       1826 non-null   int64 
 5   AY        1826 non-null   int64 
 6   AwayTeam  1826 non-null   object
 7   Date      1826 non-null   object
 8   HC        1826 non-null   int64 
 9   HF        1826 non-null   int64 
 10  HR        1826 non-null   int64 
 11  HS        1826 non-null   int64 
 12  HST       1826 non-null   int64 
 13  HTAG      1826 non-null   int64 
 14  HTHG      1826 non-null   int64 
 15  HY        1826 non-null   int64 
 16  HomeTeam  1826 non-null   object
 17  Referee   380 non-null    object
 18  league    1826 non-null   object
dtypes: int64(14), object(5)
memory usage: 285.3+ KB


Almost no column in test_df except Referee has null values. Since this column can be safely dropped, test_df will have no null values!!

We can make use of date information in many ways like identify the season, number of days since last match (to capture player fatigue), fouls or goals per game UNTIL THE LAST GAME etc.  

#### Since we are dealing with time sensitive data here, the model should not have access to data/statistics from future matches)

In [13]:
# change string column to datetime64 column

train_df["Date"] = train_df["Date"].apply(pd.to_datetime)
test_df["Date"] = test_df["Date"].apply(pd.to_datetime)

In [14]:
print(f"\nOldest date in train_df is {min(train_df['Date'])}")
print(f"Latest date in train_df is {max(train_df['Date'])}")

print(f"\nOldest date in test_df is {min(test_df['Date'])}")
print(f"Latest date in test_df is {max(test_df['Date'])}")


Oldest date in train_df is 2009-01-11 00:00:00
Latest date in train_df is 2017-12-05 00:00:00

Oldest date in test_df is 2017-01-10 00:00:00
Latest date in test_df is 2018-12-05 00:00:00


The date column has been read correctly since it matches the information given in the problem statement i.e. the matches in the training date from 2009 to 2017.  

The dates tell us that it's calendar year 2009 and NOT start-of-season 2009 for train_df. Similar observations can be made for latest date in train_df, oldest date of test_df, latest_date of test_df. We will cross-check this later in this notebook.

In [15]:
# the following columns are always non-negative integers and can never be float values. The values are always less than the max value of Int8 since there can't something like 127 (max value of signed int) corners/shots in a match. Let us change them to integer values.

columnNames = ['AC', 'AF', 'AR', 'AS', 'AST', 'AY', 'HC', 'HF', 'HR', 'HS', 'HST', 'HTAG', 'HTHG', 'HY']
for columnName in columnNames:
    if min(train_df[columnName]) < 0 or min(test_df[columnName]) < 0:
        raise Exception(f"Value under {columnName} in train_df or test_df is negative. This cannot happen. Some issue with the data!!")
    # if no issue found, change that column to integer type.
    train_df[columnName] = train_df[columnName].astype('Int8')
    test_df[columnName] = test_df[columnName].astype('Int8')

In [16]:
# the following columns are/should always be strings

columnNames = ['AwayTeam', 'HomeTeam', 'league'] # skipped Referee since we will dropping it. FTR will be looked into.
for columnName in columnNames:
    train_df[columnName] = train_df[columnName].astype('string')
    test_df[columnName] = test_df[columnName].astype('string')

In [17]:
# check for any unexpected values under the FTR column

Counter(list(train_df["FTR"].astype('string')))

Counter({'H': 5931, 'D': 3283, 'A': 3568, <NA>: 7})

In [18]:
# change FTR column to string.
train_df["FTR"] = train_df["FTR"].astype('string') # null values are taken care of automatically

In [19]:
# check for duplicated rows and keep only one occurence of the row. We'll choose the first occurence of the row. 
print(f"Number of rows in train_df = {len(train_df)}")
print(f"Number of rows in test_df = {len(test_df)}")

# drop duplicates
train_df = train_df.drop_duplicates(keep='first')
test_df = test_df.drop_duplicates(keep='first')
print("After dropping duplicates ...")

print(f"Number of rows in train_df = {len(train_df)}")
print(f"Number of rows in test_df = {len(test_df)}")


Number of rows in train_df = 12789
Number of rows in test_df = 1826
After dropping duplicates ...
Number of rows in train_df = 12785
Number of rows in test_df = 1826


Four rows from train_df where there were duplicates have been dropped.

In [20]:
# let us drop the Referee column in the test_df
test_df = test_df.drop(['Referee'], axis=1)

Once again, let us list the datatypes and number of null values under each column for train_df and test_df

In [21]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12785 entries, 0 to 12788
Data columns (total 19 columns):
 #   Column    Non-Null Count  Dtype         
---  ------    --------------  -----         
 0   AC        12780 non-null  Int8          
 1   AF        12778 non-null  Int8          
 2   AR        12780 non-null  Int8          
 3   AS        12780 non-null  Int8          
 4   AST       12780 non-null  Int8          
 5   AY        12780 non-null  Int8          
 6   AwayTeam  12782 non-null  string        
 7   Date      12782 non-null  datetime64[ns]
 8   FTR       12782 non-null  string        
 9   HC        12780 non-null  Int8          
 10  HF        12778 non-null  Int8          
 11  HR        12780 non-null  Int8          
 12  HS        12780 non-null  Int8          
 13  HST       12780 non-null  Int8          
 14  HTAG      12779 non-null  Int8          
 15  HTHG      12779 non-null  Int8          
 16  HY        12779 non-null  Int8          
 17  HomeTeam  12

In [22]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1826 entries, 0 to 379
Data columns (total 18 columns):
 #   Column    Non-Null Count  Dtype         
---  ------    --------------  -----         
 0   AC        1826 non-null   Int8          
 1   AF        1826 non-null   Int8          
 2   AR        1826 non-null   Int8          
 3   AS        1826 non-null   Int8          
 4   AST       1826 non-null   Int8          
 5   AY        1826 non-null   Int8          
 6   AwayTeam  1826 non-null   string        
 7   Date      1826 non-null   datetime64[ns]
 8   HC        1826 non-null   Int8          
 9   HF        1826 non-null   Int8          
 10  HR        1826 non-null   Int8          
 11  HS        1826 non-null   Int8          
 12  HST       1826 non-null   Int8          
 13  HTAG      1826 non-null   Int8          
 14  HTHG      1826 non-null   Int8          
 15  HY        1826 non-null   Int8          
 16  HomeTeam  1826 non-null   string        
 17  league    1826 

Get the count of null values in all columns in the two dataframes

In [23]:
train_df.isnull().sum() # number of null values by column in train_df

AC          5
AF          7
AR          5
AS          5
AST         5
AY          5
AwayTeam    3
Date        3
FTR         3
HC          5
HF          7
HR          5
HS          5
HST         5
HTAG        6
HTHG        6
HY          6
HomeTeam    3
league      0
dtype: int64

In [24]:
test_df.isnull().sum() # number of null values by column in test_df

AC          0
AF          0
AR          0
AS          0
AST         0
AY          0
AwayTeam    0
Date        0
HC          0
HF          0
HR          0
HS          0
HST         0
HTAG        0
HTHG        0
HY          0
HomeTeam    0
league      0
dtype: int64

Let us look at the rows with one or more values in the dataframes.

In [25]:
train_df[train_df.isnull().any(axis=1)] # shape = 9 rows, 19 columns

AC    AF    AR    AS   AST    AY   AwayTeam       Date   FTR    HC  \
5620      5  <NA>     0     6     3     3  Marseille 2011-09-18     H     3   
5733      1  <NA>     0     9     3     5      Nancy 2011-12-17     A     8   
7082   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>       <NA>        NaT  <NA>  <NA>   
7408   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>       Lyon 2017-04-16     A  <NA>   
9363   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>       <NA>        NaT  <NA>  <NA>   
11298  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>       Roma 2012-09-23     A  <NA>   
11644  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>       <NA>        NaT  <NA>  <NA>   
11894     5    16     0    10     1     5   Juventus 2015-02-03     D     1   
12426     7    21     0    15     5     2    Pescara 2016-08-28     A     2   

         HF    HR    HS   HST  HTAG  HTHG    HY  HomeTeam          league  
5620   <NA>     0    10     5     0     2     0      Lyon         ligue-1  
5733   <NA>     0     9     1     1     0     2      Caen         ligue-1  
7082   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>      <NA>         ligue-1  
7408   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>    Bastia         ligue-1  
9363   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>      <NA>  premier-league  
11298  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  Cagliari         serie-a  
11644  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>      <NA>         serie-a  
11894    11     1     8     3     0     0  <NA>      Roma         serie-a  
12426    12     0    13     3  <NA>  <NA>     2  Sassuolo         serie-a

Row with indices 7082, 9363, 11644 have null under all columns without any information other than the leagues they belong to.   If we knew the Home and Away teams along with the season information, we could have retrieved from outside sources and filled in the information. **Unfortunately, we will have to drop these rows.**

In [26]:
train_df = train_df.drop(axis=1, index = [7082, 9363, 11644])  # drop from train_df where all entire rows are null values

In [27]:
train_df[train_df.isnull().any(axis=1)] # check rows with one or more null values again in train_df

AC    AF    AR    AS   AST    AY   AwayTeam       Date FTR    HC  \
5620      5  <NA>     0     6     3     3  Marseille 2011-09-18   H     3   
5733      1  <NA>     0     9     3     5      Nancy 2011-12-17   A     8   
7408   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>       Lyon 2017-04-16   A  <NA>   
11298  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>       Roma 2012-09-23   A  <NA>   
11894     5    16     0    10     1     5   Juventus 2015-02-03   D     1   
12426     7    21     0    15     5     2    Pescara 2016-08-28   A     2   

         HF    HR    HS   HST  HTAG  HTHG    HY  HomeTeam   league  
5620   <NA>     0    10     5     0     2     0      Lyon  ligue-1  
5733   <NA>     0     9     1     1     0     2      Caen  ligue-1  
7408   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>    Bastia  ligue-1  
11298  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  Cagliari  serie-a  
11894    11     1     8     3     0     0  <NA>      Roma  serie-a  
12426    12     0    13     3  <NA>  <NA>     2  Sassuolo  serie-a

In [28]:
test_df[test_df.isnull().any(axis=1)] # check rows with one or more null values again in test_df

Empty DataFrame
Columns: [AC, AF, AR, AS, AST, AY, AwayTeam, Date, HC, HF, HR, HS, HST, HTAG, HTHG, HY, HomeTeam, league]
Index: []

We can get information for the missing values using Date, HomeTeam and AwayTeam using the CSVs we have downloaded. For that, let's identify the leagues we need to download.  

Please look into **0_downloadMoreData.py** file on how we can download data for each season for different leagues. Using the data downloaded, we can fill in the NA values we see train_df. Notes about these can be found [here](https://www.football-data.co.uk/notes.txt)

In [29]:
# list the leagues in both the dfs
print("Leagues in train_df ::", list(np.unique(train_df["league"])))
print("Leagues in test_df :: ", list(np.unique(test_df["league"])))

Leagues in train_df :: ['bundesliga', 'la-liga', 'ligue-1', 'premier-league', 'serie-a']
Leagues in test_df ::  ['bundesliga', 'la-liga', 'ligue-1', 'premier-league', 'serie-a']


In [30]:
# identify rows in train_df that have one or more null rows
train_df_oneOrMoreNulls = train_df[train_df.isnull().any(axis=1)]
train_df_oneOrMoreNulls

AC    AF    AR    AS   AST    AY   AwayTeam       Date FTR    HC  \
5620      5  <NA>     0     6     3     3  Marseille 2011-09-18   H     3   
5733      1  <NA>     0     9     3     5      Nancy 2011-12-17   A     8   
7408   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>       Lyon 2017-04-16   A  <NA>   
11298  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>       Roma 2012-09-23   A  <NA>   
11894     5    16     0    10     1     5   Juventus 2015-02-03   D     1   
12426     7    21     0    15     5     2    Pescara 2016-08-28   A     2   

         HF    HR    HS   HST  HTAG  HTHG    HY  HomeTeam   league  
5620   <NA>     0    10     5     0     2     0      Lyon  ligue-1  
5733   <NA>     0     9     1     1     0     2      Caen  ligue-1  
7408   <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>    Bastia  ligue-1  
11298  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  <NA>  Cagliari  serie-a  
11894    11     1     8     3     0     0  <NA>      Roma  serie-a  
12426    12     0    13     3  <NA>  <NA>     2  Sassuolo  serie-a

In [ ]:
# impute data

Our priliminary analysis of the train_df above showed that the matches are from the beginning of calendar year 2009 (not season 2009-10) and end of calendar year 2017 (not season 2016-17). Let us verify that claim without seperating the seasons.

In [31]:
for league in list(np.unique(train_df["league"])):
    print(f"League :: {league}")
    print(sorted(Counter(train_df[(train_df["league"] == league)]["Date"].dt.strftime("%m")).items()))
    print("=======\n")

League :: bundesliga
[('01', 194), ('02', 214), ('03', 185), ('04', 242), ('05', 142), ('06', 70), ('07', 72), ('08', 184), ('09', 240), ('10', 229), ('11', 213), ('12', 157)]

League :: la-liga
[('01', 296), ('02', 268), ('03', 250), ('04', 302), ('05', 201), ('06', 80), ('07', 90), ('08', 197), ('09', 289), ('10', 270), ('11', 235), ('12', 182)]

League :: ligue-1
[('01', 250), ('02', 257), ('03', 211), ('04', 260), ('05', 205), ('06', 92), ('07', 106), ('08', 269), ('09', 271), ('10', 262), ('11', 247), ('12', 230)]

League :: premier-league
[('01', 288), ('02', 217), ('03', 215), ('04', 276), ('05', 185), ('06', 79), ('07', 67), ('08', 255), ('09', 238), ('10', 273), ('11', 242), ('12', 325)]

League :: serie-a
[('01', 278), ('02', 266), ('03', 226), ('04', 265), ('05', 188), ('06', 124), ('07', 91), ('08', 173), ('09', 310), ('10', 315), ('11', 236), ('12', 188)]



We see matches in every month of the season. There seems to be some issue with the data since football leagues usually take a Summer break in these months.  

Let us verify that further by checking if any league has any break during these months. We expect to see zero matches.

In [32]:
# count the number of matches in the summer months of the year for all the leagues in the training data

for year in range(2009, 2017+1): # since train_df is from calendar year 2009 to 2017
    for league in list(np.unique(train_df["league"])):
        print(f"League :: {str(year)}" f" {league}")
        print(sorted(Counter(train_df[
                                (train_df["league"] == league) & \
                                (train_df["Date"].dt.year == year) & \
                                ((train_df["Date"].dt.month == 6) | (train_df["Date"].dt.month == 7)) # summer months
                            ]["Date"].dt.strftime("%m")).items() ))
        print("=======")
    print("***"*10)

League :: 2009 bundesliga
[('06', 3), ('07', 6)]
League :: 2009 la-liga
[('06', 6), ('07', 4)]
League :: 2009 ligue-1
[('06', 4), ('07', 7)]
League :: 2009 premier-league
[('06', 2), ('07', 5)]
League :: 2009 serie-a
[('06', 8), ('07', 2)]
******************************
League :: 2010 bundesliga
[('06', 18), ('07', 7)]
League :: 2010 la-liga
[('06', 9), ('07', 20)]
League :: 2010 ligue-1
[('06', 19), ('07', 21)]
League :: 2010 premier-league
[('06', 19), ('07', 6)]
League :: 2010 serie-a
[('06', 17), ('07', 24)]
******************************
League :: 2011 bundesliga
[('06', 11), ('07', 11)]
League :: 2011 la-liga
[('06', 16), ('07', 9)]
League :: 2011 ligue-1
[('06', 23), ('07', 10)]
League :: 2011 premier-league
[('06', 7), ('07', 7)]
League :: 2011 serie-a
[('06', 32), ('07', 2)]
******************************
League :: 2012 bundesliga
[('06', 5), ('07', 11)]
League :: 2012 la-liga
[('06', 5), ('07', 16)]
League :: 2012 ligue-1
[('06', 10), ('07', 19)]
League :: 2012 premier-league

Let's randomly pick up some of leagues' seasons and view these rows in the train_df

In [71]:
# Premier League matches in June and July 2014
train_df[(train_df["league"] == "premier-league") & (train_df["Date"].dt.year == 2014) & ((train_df["Date"].dt.month == 6) | (train_df["Date"].dt.month == 7))]

AC  AF  AR  AS  AST  AY        AwayTeam       Date FTR  HC  HF  HR  HS  \
9123   2  16   0   6    3   1       West Brom 2014-06-12   D   3  10   0  12   
9124   7  15   0   7    1   3      Sunderland 2014-06-12   D   5  12   0  15   
9125   7  11   0   9    2   3         Everton 2014-06-12   H  11   8   0  19   
9126  10   6   0  26    8   3         Chelsea 2014-06-12   H   1   8   1   9   
9127  11  12   0  15    3   1         Burnley 2014-06-12   H   3  12   1  11   
9128   9  14   1  15    6   2         Arsenal 2014-06-12   H   3  17   0  13   
9129  12  10   0  16    4   0  Crystal Palace 2014-06-12   D   2  11   0  14   
9130   5  14   1  10    4   4       Leicester 2014-07-12   H   5   9   0  16   
9131   4  18   1  11    2   1         Swansea 2014-07-12   H   7  11   0  15   

      HST  HTAG  HTHG  HY     HomeTeam          league  
9123    2     0     0   1         Hull  premier-league  
9124    2     0     0   1    Liverpool  premier-league  
9125    3     0     1   3     Man City  premier-league  
9126    3     0     0   2    Newcastle  premier-league  
9127    6     0     0   1          QPR  premier-league  
9128    4     0     3   3        Stoke  premier-league  
9129    3     0     0   1    Tottenham  premier-league  
9130    7     1     1   4  Aston Villa  premier-league  
9131    7     1     1   0     West Ham  premier-league

In [69]:
# Bundesliga matches in June and July 2016
train_df[(train_df["league"] == "bundesliga") & (train_df["Date"].dt.year == 2016) & ((train_df["Date"].dt.month == 6) | (train_df["Date"].dt.month == 7))]

AC  AF  AR  AS  AST  AY       AwayTeam       Date FTR  HC  HF  HR  HS  \
1702   7  15   1  16    9   1      Stuttgart 2016-06-02   A   2   9   1  17   
1703   4  14   0  14    2   2          Mainz 2016-06-02   A   3  20   0   9   
1704   3  16   0   9    2   2       Dortmund 2016-06-02   D   3  11   0  10   
1705   3  22   0   7    2   3       Augsburg 2016-06-02   H   8  17   0  24   
1706   8  11   1   9    1   0  Bayern Munich 2016-06-02   D   6  17   0   6   
1707   6  14   0  14    2   3      Wolfsburg 2016-06-02   H   6  15   0  15   
1708  10   5   0  20    6   2        FC Koln 2016-07-02   D   4  17   0   5   
1709   7  15   0  11    5   3      Darmstadt 2016-07-02   A   8  17   0  12   
1753   2   9   0   3    1   1         Hertha 2016-06-03   H   3  12   0  14   
1754   1  18   0  15    3   5      Darmstadt 2016-06-03   D   3  17   1  11   
1818   5  12   0  13    2   3       Dortmund 2016-07-05   H   3  20   0   6   
1819   7  20   0  13    1   2  Werder Bremen 2016-07-05   D   8  20   0   9   
1820   4  10   0  11    6   0      Wolfsburg 2016-07-05   A   5  18   0   5   
1821   5  20   0  15    4   2     Hoffenheim 2016-07-05   H   3  20   0  15   
1822   1  22   1   7    3   1      Darmstadt 2016-07-05   A  10  18   0  17   
1823   3  15   0  12    6   3  Bayern Munich 2016-07-05   A   4  17   0  16   
1824   3   9   0  17    8   2     Leverkusen 2016-07-05   H   6  16   0  14   
1825   2  17   0   5    2   5       Augsburg 2016-07-05   D   9  10   0  20   
1826   9  17   0  19   11   2          Mainz 2016-07-05   A   6  11   0   8   
1924   6  12   0  11    3   3          Mainz 2016-06-11   H   3  13   0  15   
1925   6  14   0   8    5   3  Werder Bremen 2016-06-11   H   3  13   0  24   

      HST  HTAG  HTHG  HY       HomeTeam      league  
1702    7     2     0   1  Ein Frankfurt  bundesliga  
1703    2     1     0   1       Hannover  bundesliga  
1704    4     0     0   0         Hertha  bundesliga  
1705    4     1     0   2     Ingolstadt  bundesliga  
1706    2     0     0   0     Leverkusen  bundesliga  
1707    3     0     2   2     Schalke 04  bundesliga  
1708    4     1     0   5        Hamburg  bundesliga  
1709    1     1     0   1     Hoffenheim  bundesliga  
1753    5     0     0   4        Hamburg  bundesliga  
1754    4     0     0   0          Mainz  bundesliga  
1818    4     0     1   5  Ein Frankfurt  bundesliga  
1819    4     0     0   3        FC Koln  bundesliga  
1820    0     0     0   0        Hamburg  bundesliga  
1821    4     0     1   3       Hannover  bundesliga  
1822    4     1     1   3         Hertha  bundesliga  
1823    4     2     1   2     Ingolstadt  bundesliga  
1824    6     1     1   2     M'gladbach  bundesliga  
1825    5     0     0   1     Schalke 04  bundesliga  
1826    3     1     1   3      Stuttgart  bundesliga  
1924    5     0     3   0     RB Leipzig  bundesliga  
1925    6     1     2   2     Schalke 04  bundesliga

We see many matches here but looking at data on the internet on Wikipedia (assuming no one has messed with the data), we can see that the season did end in the May of the respective years. 

The [2013-14 PL season](https://en.wikipedia.org/wiki/2013–14_Premier_League) started on 17 August 2013, and concluded on 11 May 2014.  
The [2014-15 PL season](https://en.wikipedia.org/wiki/2014–15_Premier_League) started on 16 August 2014, and concluded on 24 May 2015.


Let us check the start and end date of each season for every league **using the data we downloaded from [www.football-data.co.uk](www.football-data.co.uk)**

In [73]:
# since train_df is from calendar year 2009 to 2017
# therefore, first season is 2008-09; last season is 2017-18

for year in range(2008, 2017+1):
    season = f"{str(year)}-{str(year+1)[-2:]}"
    seasonId = str(year)[-2:] + str(year+1)[-2:]
    for leagueName in list(np.unique(train_df["league"])):
        seasonId = str(year)[-2:] + str(year+1)[-2:]
        currSeasonCurrLeagueDF = pd.read_csv(os.path.join("downloaded_data", f"{leagueName}_{seasonId}.csv")).dropna(how='all')

        firstMatchDate = pd.to_datetime(currSeasonCurrLeagueDF.iloc[0, 1])
        lastMatchDate = pd.to_datetime(currSeasonCurrLeagueDF.iloc[-1, 1])
        firstMatchDateFullString = firstMatchDate.strftime('%d %B %Y')
        lastMatchDateFullString = lastMatchDate.strftime('%d %B %Y')
        
        # catch seasons which end beyond May of the next year
        seasonRunsDuringJuneJuly = "-- ran beyond May" if lastMatchDate.year == (year+1) and lastMatchDate.month > 5 else ""
        
        print(f"{season} {leagueName} season was between {firstMatchDateFullString} and {lastMatchDateFullString} {seasonRunsDuringJuneJuly}")
        
    print("=========")

2008-09 bundesliga season was between 15 August 2008 and 23 May 2009 
2008-09 la-liga season was between 30 August 2008 and 31 May 2009 
2008-09 ligue-1 season was between 08 September 2008 and 30 May 2009 
2008-09 premier-league season was between 16 August 2008 and 24 May 2009 
2008-09 serie-a season was between 30 August 2008 and 31 May 2009 
2009-10 bundesliga season was between 08 July 2009 and 05 August 2010 -- ran beyond May
2009-10 la-liga season was between 29 August 2009 and 16 May 2010 
2009-10 ligue-1 season was between 08 August 2009 and 15 May 2010 
2009-10 premier-league season was between 15 August 2009 and 05 September 2010 -- ran beyond May
2009-10 serie-a season was between 22 August 2009 and 16 May 2010 
2010-11 bundesliga season was between 20 August 2010 and 14 May 2011 
2010-11 la-liga season was between 28 August 2010 and 21 May 2011 
2010-11 ligue-1 season was between 08 July 2010 and 29 May 2011 
2010-11 premier-league season was between 14 August 2010 and 22 

The data downloaded from football.co.uk agrees with the train_df for Premier League in June, July 2014 i.e. there were matches played.  

However, we do not see any matches played in the Bundesliga in June, July 2016 according to downloaded_data although train_df has records of this.  

Please note that I have cross-checked only if there were matches played and not the actual statistics. 

**I just wanted to point this discrepancy in the data due to my knowledge in the matter. However, for the purposes of this exercise we will ignore this issue FOR NOW and proceed with whatever is in train_df.**  

I had planned to get information like 
- win/draw odds of HomeTeam/AwayTeam  ** *because betting odds capture what people are thinking as to who'll win -- can be really good predictor of the winning team * ** ,  
- number of times the HomeTeam/AwayTeam hit the woodwork ** *because the team hitting the woodwork is attacking well and has a good shot at scoring a goal the next time they try. However, this is not a necessary * ** ,  
- number of freekicks conceded by the HomeTeam/AwayTeam ** *because the team conceding a lot of freekicks is not good at defending. Could signal a weak team. But, some strong teams too play aggressively. Again, this is not necessary. * ** ,  
- number of offsides for HomeTeam/AwayTeam ** * This could be interpreted in two ways. Either the defending team has a great offside trap mechanism or the attacking team is able to find space to counter-attack but failed. I can explain more about this I go through my code.  * **  

from the downloaded_data.   

But this information will not be available for some of seasons since most of them ended in May according to www.football-data.co.uk. But train_df says otherwise.